# Generated by Django 4.2.2 on 2023-07-11 18:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smps', '0003_device_sensormaster_tower_sensorvalues_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tower',
            name='assigned',
            field=models.IntegerField(choices=[(0, 'Not Assigned'), (1, 'Assigned')], default=0),
        ),
        migrations.AlterField(
            model_name='tower',
            name='contractor_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='smps.user'),
        ),
    ]
