# Generated by Django 4.2.2 on 2023-07-12 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smps', '0005_remove_tower_contractor_id_tower_area_manager_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tower',
            name='area_manager_id',
            field=models.ForeignKey(db_column='area_manager_id', on_delete=django.db.models.deletion.CASCADE, to='smps.user'),
        ),
    ]
