# Generated by Django 4.2.2 on 2023-07-12 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smps', '0006_alter_tower_area_manager_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tower',
            name='area_manager_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smps.user'),
        ),
    ]
