# Generated by Django 4.2.2 on 2023-07-12 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smps', '0008_rename_area_manager_id_tower_area_manager'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operator',
            name='lat',
        ),
        migrations.RemoveField(
            model_name='operator',
            name='long',
        ),
    ]
